# Generated by Django 5.1.7 on 2025-03-31 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='doctor_id',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='patient_id',
        ),
    ]
